version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_PORT=3000
      - NODE_ENV=production
      - MONGO_URL=mongodb://root:root@mongo:27017/admin
      - MONGO_DATABASE=solus
      - JWT_SECRET=sMDe63B42DuHcL4z_aRv4k%Nnru%FvBm
    expose:
      - 3000
    volumes:
      - .:/app
    links:
      - mongo:mongo
    depends_on:
      - mongo
      
  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=solus
